#!/bin/bash

# cp this file to /usr/bin and it will magically be a custom git command!
# Usage: git publish-website

# Run the specs first
rspec

# Only if they pass, can we deploy to production
if [ $? -ne 0 ]; then
  echo
  echo "*** Halting deploy due to spec fail ***"
  echo
else
  echo
  echo "*** Specs pass so commencing deployment ***"
  echo
  git branch -D master
  git checkout -b master
  git filter-branch --subdirectory-filter _site/ -f
  git checkout source
  git push --all origin
fi
